services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api.dashboard=true"
      - "--log.level=INFO" # Lo volvemos a INFO, ya no necesitamos DEBUG
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.email=alonso@nuxapower.cl"
      - "--certificatesresolvers.letsencrypt.acme.storage=/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_acme:/acme
    networks:
      - traefik
    labels:
      - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.nuxapower.cl/"
      - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Email,Remote-Name"
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.nuxapower.cl`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
      - "traefik.http.routers.traefik.middlewares=authelia@docker"

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    volumes:
      # Montamos los archivos secretos desde donde el workflow los copiará
      - ./authelia/configuration.yml:/config/configuration.yml:ro
      - ./authelia/users_database.yml:/config/users_database.yml:ro
      - authelia_data:/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.authelia.rule=Host(`auth.nuxapower.cl`)"
      - "traefik.http.routers.authelia.service=authelia"
      - "traefik.http.routers.authelia.entrypoints=websecure"
      - "traefik.http.routers.authelia.tls.certresolver=letsencrypt"
      - "traefik.http.services.authelia.loadbalancer.server.port=9091"

  filestash:
    image: machines/filestash
    container_name: filestash
    restart: unless-stopped
    environment:
      # --- ESTA ES LA MAGIA ---
      # Le decimos a FileStash que la autenticación es manejada por el proxy.
      - APPLICATION_AUTH_METHOD=proxy
      # Le decimos que el nombre de usuario viene en la cabecera 'Remote-User'.
      - APPLICATION_PROXY_AUTH_HEADER=Remote-User
    volumes:
      # Un solo volumen para toda la data y configuración de FileStash.
      - filestash_data:/app/data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      # Usaremos el mismo subdominio para no tener que cambiar el DNS.
      - "traefik.http.routers.filestash.rule=Host(`files.nuxapower.cl`)"
      - "traefik.http.routers.filestash.service=filestash"
      - "traefik.http.routers.filestash.entrypoints=websecure"
      - "traefik.http.routers.filestash.tls.certresolver=letsencrypt"
      - "traefik.http.routers.filestash.middlewares=authelia@docker"
      - "traefik.http.services.filestash.loadbalancer.server.port=8334"

networks:
  traefik:
    driver: bridge

volumes:
  traefik_acme:
  authelia_data:
  filestash_data: