name: Deploy to Hetzner (Self-Hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1. Clona el repositorio a la carpeta de trabajo temporal del runner
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Copia los archivos privados desde su nueva ubicación permanente
      - name: Copy private configuration files
        run: |
          echo "==> Copiando archivos privados desde ~/self-hosted-secrets..."
          
          # Copia el .env desde el "baúl" a la carpeta de trabajo actual
          cp ~/self-hosted-secrets/.env .
          
          # Copia la configuración de authelia desde el "baúl"
          cp -r ~/self-hosted-secrets/authelia .
          
          echo "==> Archivos copiados."

      # 3. Despliega la aplicación
      - name: Deploy Application
        run: |
          echo "==> Desplegando los cambios con Docker Compose..."
          docker compose --project-directory . up -d --pull --force-recreate
          
          echo "==> Limpiando imágenes de Docker antiguas..."
          docker image prune -f
          
          echo "==> ¡Deploy completado!"